lib/vigilant_palm_tree_web/router.ex
defmodule VigilantPalmTreeWeb.Router do
  use VigilantPalmTreeWeb, :router

  import VigilantPalmTreeWeb.UserAuth

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {VigilantPalmTreeWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug :fetch_current_user
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", VigilantPalmTreeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/", PageController, :index

    get "/report", ReportController, :index

    resources "/expenses", ExpenseController
    resources "/revenues", RevenueController
  end

  # Other scopes may use custom stacks.
  # scope "/api", VigilantPalmTreeWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: VigilantPalmTreeWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end

  ## Authentication routes

  scope "/", VigilantPalmTreeWeb do
    pipe_through [:browser, :redirect_if_user_is_authenticated]

    get "/users/register", UserRegistrationController, :new
    post "/users/register", UserRegistrationController, :create
    get "/users/log_in", UserSessionController, :new
    post "/users/log_in", UserSessionController, :create
    get "/users/reset_password", UserResetPasswordController, :new
    post "/users/reset_password", UserResetPasswordController, :create
    get "/users/reset_password/:token", UserResetPasswordController, :edit
    put "/users/reset_password/:token", UserResetPasswordController, :update
  end

  scope "/", VigilantPalmTreeWeb do
    pipe_through [:browser, :require_authenticated_user]

    get "/users/settings", UserSettingsController, :edit
    put "/users/settings", UserSettingsController, :update
    get "/users/settings/confirm_email/:token", UserSettingsController, :confirm_email
  end

  scope "/", VigilantPalmTreeWeb do
    pipe_through [:browser]

    delete "/users/log_out", UserSessionController, :delete
    get "/users/confirm", UserConfirmationController, :new
    post "/users/confirm", UserConfirmationController, :create
    get "/users/confirm/:token", UserConfirmationController, :edit
    post "/users/confirm/:token", UserConfirmationController, :update
  end
end

lib/vigilant_palm_tree_web/controllers/user_session_controller.ex
defmodule VigilantPalmTreeWeb.UserSessionController do
  use VigilantPalmTreeWeb, :controller

  alias VigilantPalmTree.Accounts
  alias VigilantPalmTreeWeb.UserAuth

  def new(conn, _params) do
    render(conn, "new.html", error_message: nil)
  end

  def create(conn, %{"user" => user_params}) do
    %{"email" => email, "password" => password} = user_params

    if user = Accounts.get_user_by_email_and_password(email, password) do
      UserAuth.log_in_user(conn, user, user_params)
    else
      # In order to prevent user enumeration attacks, don't disclose whether the email is registered.
      render(conn, "new.html", error_message: "Invalid email or password")
    end
  end

  def delete(conn, _params) do
    conn
    |> put_flash(:info, "Logged out successfully.")
    |> UserAuth.log_out_user()
  end
end

lib/vigilant_palm_tree_web/views/user_session_view.ex
defmodule VigilantPalmTreeWeb.UserSessionView do
  use VigilantPalmTreeWeb, :view
end

lib/vigilant_palm_tree_web/templates/user_session/new.html.heex
<div>
  <h1>Log in</h1>

  <.form let={f} for={@conn} action={Routes.user_session_path(@conn, :create)} as={:user}>
    <%= if @error_message do %>
      <div class="alert alert-danger">
        <p><%= @error_message %></p>
      </div>
    <% end %>

    <div class="mb-3">
      <%= label f, :email, class: "form-label" %>
      <%= email_input f, :email, required: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= label f, :password, class: "form-label" %>
      <%= password_input f, :password, required: true, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= label f, :remember_me, "Keep me logged in for 60 days" %>
      <%= checkbox f, :remember_me %>
    </div>

    <div>
      <%= submit "Log in", class: "btn btn-primary" %>
    </div>
  </.form>

  <p>
    <%= link "Register", to: Routes.user_registration_path(@conn, :new), class: "btn btn-link" %> |
    <%= link "Forgot your password?", to: Routes.user_reset_password_path(@conn, :new), class: "btn btn-link" %>
  </p>

</div>